In [1]:
!pip install --upgrade pandas

Collecting pandas
  Downloading https://files.pythonhosted.org/packages/52/3f/f6a428599e0d4497e1595030965b5ba455fd8ade6e977e3c819973c4b41d/pandas-0.25.3-cp36-cp36m-manylinux1_x86_64.whl (10.4MB)
     |████████████████████████████████| 10.4MB 1.3MB/s eta 0:00:01
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in /home/ec2-user/anaconda3/envs/yelp/lib/python3.6/site-packages (from pandas) (2.8.0)
Requirement already satisfied, skipping upgrade: numpy>=1.13.3 in /home/ec2-user/anaconda3/envs/yelp/lib/python3.6/site-packages (from pandas) (1.16.2)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/yelp/lib/python3.6/site-packages (from pandas) (2019.3)
Requirement already satisfied, skipping upgrade: six>=1.5 in /home/ec2-user/anaconda3/envs/yelp/lib/python3.6/site-packages (from python-dateutil>=2.6.1->pandas) (1.12.0)
Installing collected packages: pandas
  Found existing installation: pandas 0.24.1
    Uninstalling pandas-0.24.1:
      Successfully uninstalled pandas-0.24.1
Successfully installed pandas-0.25.3

In [2]:
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
train_review = pd.read_json('../data/restaurant/train_yelp_academic_dataset_review.json')
test_review = pd.read_json('../data/restaurant/test_yelp_academic_dataset_review.json')
user = pd.read_json('../data/restaurant/yelp_academic_dataset_user.json')
business = pd.read_json('../data/restaurant/yelp_academic_dataset_business.json')

In [4]:
train_review.to_json('../data/restaurant/train_yelp_academic_dataset_review.json', orient='records', lines=True)
test_review.to_json('../data/restaurant/test_yelp_academic_dataset_review.json', orient='records', lines=True)
user.to_json('../data/restaurant/yelp_academic_dataset_user.json', orient='records', lines=True)
business.to_json('../data/restaurant/yelp_academic_dataset_business.json', orient='records', lines=True)

In [3]:
def tokenize(row):
    words = str(row).split(',')
    words = [word.strip() for word in words]
    return words

user['friends'] = user['friends'].apply(tokenize)

In [4]:
user = user.explode('friends')

In [5]:
user = user[['user_id', 'friends']]

In [6]:
user

                        user_id                 friends
0        2K62MJ4CJ19L8Tp5pRfjfQ  ZJfwkdJMex21dGHfQ3YgTg
0        2K62MJ4CJ19L8Tp5pRfjfQ  603oDa3dGdJyfkq2RoH2Dw
0        2K62MJ4CJ19L8Tp5pRfjfQ  XombY1IoKITwJE7A_Z0z-g
0        2K62MJ4CJ19L8Tp5pRfjfQ  Ov_tXNoHw1CZWVIcjzvaLQ
0        2K62MJ4CJ19L8Tp5pRfjfQ  2LCZ7G3Jtleu_xMQ2fWTqQ
...                         ...                     ...
4580256  Vy8pwj93dTmVbc324hszbg  Ye9kknVK9BM26hY_brv_hg
4580280  fujMP2_dR64u7w945kzoCw                    None
4580282  w7peCneijVMdqbVsImulmA                    None
4580284  akwpK76zSPvJPVaA2BQlpQ                    None
4580296  ZO8h27XOn_XFKLLRRrLp0g                    None

[59936523 rows x 2 columns]

In [9]:
user = user[user['friends'] != 'None']

In [10]:
user

                        user_id                 friends
0        2K62MJ4CJ19L8Tp5pRfjfQ  ZJfwkdJMex21dGHfQ3YgTg
0        2K62MJ4CJ19L8Tp5pRfjfQ  603oDa3dGdJyfkq2RoH2Dw
0        2K62MJ4CJ19L8Tp5pRfjfQ  XombY1IoKITwJE7A_Z0z-g
0        2K62MJ4CJ19L8Tp5pRfjfQ  Ov_tXNoHw1CZWVIcjzvaLQ
0        2K62MJ4CJ19L8Tp5pRfjfQ  2LCZ7G3Jtleu_xMQ2fWTqQ
...                         ...                     ...
4580248  X2CfMLXq937zxuqq1_wDEw  H040kgBYjOChvsKqvy4YnA
4580248  X2CfMLXq937zxuqq1_wDEw  og3gjB0zMlOLPqbmKmpR5w
4580256  Vy8pwj93dTmVbc324hszbg  QxTcVl_TKBB65LIAq5oASg
4580256  Vy8pwj93dTmVbc324hszbg  viNVdK-BxmF0ZsP6ZF8Suw
4580256  Vy8pwj93dTmVbc324hszbg  Ye9kknVK9BM26hY_brv_hg

[59481750 rows x 2 columns]

In [14]:
user_item = train_review[['business_id', 'user_id']]

In [16]:
user_item = pd.merge(user_item, business, on='business_id', how='left')

In [18]:
user_item = user_item[['business_id', 'user_id', 'attributes', 'category']]

In [19]:
user = pd.merge(user_item, user, on='user_id', how='left', suffixes=('_left', ''))

In [23]:
user = pd.merge(user, user_item, left_on='friends', right_on='user_id', suffixes=('_user', '_friend'))

MemoryError:

In [22]:
user

,business_id,user_id,attributes,category,friends
0,gBfPyzPRmeOaj3SdcIj0Rw,BKcmc3Rj6L1EHeou_07IUw,"{'Ambience': '{'romantic': False, 'intimate': ...","[Restaurants, Japanese, Sushi Bars, Bars, Nigh...",NaN
1,GZONBn0K1yp2aaD-l8debQ,_s7MCXeAZ5JhwOxVLDjHOQ,"{'RestaurantsPriceRange2': '2', 'RestaurantsTa...","[Nightlife, Restaurants, Cocktail Bars, Bars, ...",6_LzmP5n2kih0j09ARlVQg
2,GZONBn0K1yp2aaD-l8debQ,_s7MCXeAZ5JhwOxVLDjHOQ,"{'RestaurantsPriceRange2': '2', 'RestaurantsTa...","[Nightlife, Restaurants, Cocktail Bars, Bars, ...",3Oxk5kKp9x2-xzyACRPoIA
3,GZONBn0K1yp2aaD-l8debQ,_s7MCXeAZ5JhwOxVLDjHOQ,"{'RestaurantsPriceRange2': '2', 'RestaurantsTa...","[Nightlife, Restaurants, Cocktail Bars, Bars, ...",EvdMsbv1ydlRpdk_iDLacw
4,GZONBn0K1yp2aaD-l8debQ,_s7MCXeAZ5JhwOxVLDjHOQ,"{'RestaurantsPriceRange2': '2', 'RestaurantsTa...","[Nightlife, Restaurants, Cocktail Bars, Bars, ...",p3eRNK0jK8mNS2nFvS_vug
...,...,...,...,...,...
147891692,1FlIbmN4aNJuXsGK0shnfQ,3izmsMz2YIYWPa7dypsZJg,"{'GoodForMeal': '{'dessert': False, 'latenight...","[Southern, Sandwiches, Soul Food, Restaurants,...",cCvtUXxbNPBSbdBAEpRmXg
147891693,1FlIbmN4aNJuXsGK0shnfQ,3izmsMz2YIYWPa7dypsZJg,"{'GoodForMeal': '{'dessert': False, 'latenight...","[Southern, Sandwiches, Soul Food, Restaurants,...",5fBddMnHpuNkgrtv7cjZgA
147891694,1FlIbmN4aNJuXsGK0shnfQ,3izmsMz2YIYWPa7dypsZJg,"{'GoodForMeal': '{'dessert': False, 'latenight...","[Southern, Sandwiches, Soul Food, Restaurants,...",Z9niGcEPPTHeRYX5g84oWg
147891695,1FlIbmN4aNJuXsGK0shnfQ,3izmsMz2YIYWPa7dypsZJg,"{'GoodForMeal': '{'dessert': False, 'latenight...","[Southern, Sandwiches, Soul Food, Restaurants,...",Lp_1XV7GEW-tVrQ0sRr5Qg
147891696,1FlIbmN4aNJuXsGK0shnfQ,3izmsMz2YIYWPa7dypsZJg,"{'GoodForMeal': '{'dessert': False, 'latenight...","[Southern, Sandwiches, Soul Food, Restaurants,...",k3Vj-eW_NS9SpMXBnfsGQQ